from datetime import datetime
import os
from model import setData
from Generate_Calendar import Calendar 
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QFileDialog
import pandas as pd
import numpy as np


class Ui_MainWindow(object):
    
    def __init__(self):
        self.changeTab = False
        self.RollDates = []
        self.HolidayList = []
        self.calgen_dates = []
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(703, 456)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../EVS.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 661, 411))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.pushButton = QtWidgets.QPushButton(self.tab_1)
        self.pushButton.setGeometry(QtCore.QRect(470, 340, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_1)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 20, 351, 121))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.startDate = QtWidgets.QDateEdit(self.groupBox_6)
        self.startDate.setGeometry(QtCore.QRect(20, 70, 111, 31))
        self.startDate.setCalendarPopup(True)
        self.startDate.setObjectName("startDate")
        self.endDate = QtWidgets.QDateEdit(self.groupBox_6)
        self.endDate.setGeometry(QtCore.QRect(210, 70, 111, 31))
        self.endDate.setCalendarPopup(True)
        self.endDate.setObjectName("endDate")
        self.label_3 = QtWidgets.QLabel(self.groupBox_6)
        self.label_3.setGeometry(QtCore.QRect(40, 50, 71, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_4.setGeometry(QtCore.QRect(230, 50, 71, 21))
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 10, 161, 31))
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_1)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 150, 351, 111))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit.setGeometry(QtCore.QRect(30, 30, 81, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.spinBox_4 = QtWidgets.QSpinBox(self.groupBox_7)
        self.spinBox_4.setGeometry(QtCore.QRect(230, 30, 41, 31))
        self.spinBox_4.setObjectName("spinBox_4")
        self.spinBox_5 = QtWidgets.QSpinBox(self.groupBox_7)
        self.spinBox_5.setGeometry(QtCore.QRect(290, 30, 41, 31))
        self.spinBox_5.setObjectName("spinBox_5")
        self.label_10 = QtWidgets.QLabel(self.groupBox_7)
        self.label_10.setGeometry(QtCore.QRect(160, 30, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_6.setGeometry(QtCore.QRect(150, 70, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_11 = QtWidgets.QLabel(self.groupBox_7)
        self.label_11.setGeometry(QtCore.QRect(40, 70, 91, 31))
        self.label_11.setObjectName("label_11")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_1)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 270, 351, 101))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_8)
        self.radioButton.setGeometry(QtCore.QRect(50, 20, 81, 31))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_8)
        self.radioButton_2.setGeometry(QtCore.QRect(160, 20, 161, 31))
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox_8)
        self.label_8.setGeometry(QtCore.QRect(30, 60, 91, 31))
        self.label_8.setObjectName("label_8")
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox_8)
        self.spinBox_3.setGeometry(QtCore.QRect(120, 60, 51, 31))
        self.spinBox_3.setObjectName("spinBox_3")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_5.setGeometry(QtCore.QRect(200, 60, 141, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_1)
        self.groupBox_9.setGeometry(QtCore.QRect(380, 10, 271, 211))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_9)
        self.radioButton_3.setGeometry(QtCore.QRect(10, 20, 91, 31))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_9)
        self.radioButton_4.setGeometry(QtCore.QRect(10, 130, 121, 41))
        self.radioButton_4.setObjectName("radioButton_4")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_7.setGeometry(QtCore.QRect(90, 180, 171, 21))
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.frame = QtWidgets.QFrame(self.groupBox_9)
        self.frame.setEnabled(False)
        self.frame.setGeometry(QtCore.QRect(10, 50, 251, 71))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.checkBox_20 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_20.setGeometry(QtCore.QRect(10, 0, 121, 23))
        self.checkBox_20.setObjectName("checkBox_20")
        self.checkBox_18 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_18.setGeometry(QtCore.QRect(10, 40, 141, 23))
        self.checkBox_18.setObjectName("checkBox_18")
        self.checkBox_17 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_17.setGeometry(QtCore.QRect(160, 40, 101, 23))
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkBox_19 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_19.setGeometry(QtCore.QRect(160, 0, 101, 23))
        self.checkBox_19.setObjectName("checkBox_19")
        self.toolButton_2 = QtWidgets.QToolButton(self.groupBox_9)
        self.toolButton_2.setEnabled(False)
        self.toolButton_2.setGeometry(QtCore.QRect(140, 140, 81, 31))
        self.toolButton_2.setObjectName("toolButton_2")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_1)
        self.groupBox_10.setGeometry(QtCore.QRect(380, 230, 271, 101))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.checkBox_21 = QtWidgets.QCheckBox(self.groupBox_10)
        self.checkBox_21.setGeometry(QtCore.QRect(30, 30, 101, 21))
        self.checkBox_21.setObjectName("checkBox_21")
        self.checkBox_22 = QtWidgets.QCheckBox(self.groupBox_10)
        self.checkBox_22.setGeometry(QtCore.QRect(30, 70, 141, 21))
        self.checkBox_22.setObjectName("checkBox_22")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_8.setEnabled(False)
        self.lineEdit_8.setGeometry(QtCore.QRect(130, 30, 121, 21))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.toolButton = QtWidgets.QToolButton(self.groupBox_10)
        self.toolButton.setEnabled(False)
        self.toolButton.setGeometry(QtCore.QRect(200, 70, 32, 25))
        self.toolButton.setObjectName("toolButton")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 341, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 0, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(210, 0, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit_2.setGeometry(QtCore.QRect(200, 30, 101, 31))
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit.setGeometry(QtCore.QRect(30, 30, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.dateEdit.setFont(font)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setEnabled(False)
        self.groupBox_3.setGeometry(QtCore.QRect(370, 20, 271, 151))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_8.setGeometry(QtCore.QRect(50, 70, 151, 21))
        self.radioButton_8.setObjectName("radioButton_8")
        self.radioButton_9 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_9.setGeometry(QtCore.QRect(50, 90, 151, 31))
        self.radioButton_9.setObjectName("radioButton_9")
        self.radioButton_10 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_10.setGeometry(QtCore.QRect(50, 120, 171, 21))
        self.radioButton_10.setObjectName("radioButton_10")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_3.setEnabled(False)
        self.lineEdit_3.setGeometry(QtCore.QRect(130, 10, 121, 21))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(30, 40, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 10, 81, 21))
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setEnabled(False)
        self.groupBox_4.setGeometry(QtCore.QRect(370, 200, 271, 91))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_2.setGeometry(QtCore.QRect(190, 10, 41, 21))
        self.spinBox_2.setObjectName("spinBox_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(40, 10, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_2.setGeometry(QtCore.QRect(20, 50, 131, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_3.setGeometry(QtCore.QRect(160, 50, 91, 31))
        self.comboBox_3.setObjectName("comboBox_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 340, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(240, 340, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.checkBox = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox.setGeometry(QtCore.QRect(450, 0, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_2.setGeometry(QtCore.QRect(450, 180, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.groupBox1 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox1.setGeometry(QtCore.QRect(370, 300, 271, 81))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox1.setFont(font)
        self.groupBox1.setObjectName("groupBox1")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox1)
        self.checkBox_3.setEnabled(False)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 20, 181, 21))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox1)
        self.checkBox_4.setGeometry(QtCore.QRect(20, 40, 131, 31))
        self.checkBox_4.setObjectName("checkBox_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox1)
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setGeometry(QtCore.QRect(130, 50, 121, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 90, 341, 161))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_7 = QtWidgets.QLabel(self.groupBox_5)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBox.setGeometry(QtCore.QRect(140, 20, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spinBox.setFont(font)
        self.spinBox.setObjectName("spinBox")
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_5.setGeometry(QtCore.QRect(200, 20, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setObjectName("comboBox_5")
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        self.label_9.setGeometry(QtCore.QRect(20, 90, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.radioButton_13 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_13.setGeometry(QtCore.QRect(130, 70, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_13.setFont(font)
        self.radioButton_13.setObjectName("radioButton_13")
        self.radioButton_14 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_14.setGeometry(QtCore.QRect(160, 130, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_14.setFont(font)
        self.radioButton_14.setObjectName("radioButton_14")
        self.radioButton_15 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_15.setGeometry(QtCore.QRect(130, 100, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_15.setFont(font)
        self.radioButton_15.setObjectName("radioButton_15")
        self.radioButton_16 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_16.setGeometry(QtCore.QRect(250, 100, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_16.setFont(font)
        self.radioButton_16.setObjectName("radioButton_16")
        self.radioButton_17 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_17.setGeometry(QtCore.QRect(250, 70, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_17.setFont(font)
        self.radioButton_17.setObjectName("radioButton_17")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setEnabled(False)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 250, 341, 81))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_5.setGeometry(QtCore.QRect(20, 10, 61, 23))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_6.setGeometry(QtCore.QRect(70, 10, 61, 23))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_7.setGeometry(QtCore.QRect(20, 50, 61, 23))
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_8.setGeometry(QtCore.QRect(70, 50, 61, 23))
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_9.setGeometry(QtCore.QRect(120, 10, 61, 23))
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_10.setGeometry(QtCore.QRect(120, 50, 61, 23))
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_11 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_11.setGeometry(QtCore.QRect(170, 50, 61, 23))
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_12.setGeometry(QtCore.QRect(170, 10, 61, 23))
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_13 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_13.setGeometry(QtCore.QRect(220, 12, 71, 21))
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_14 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_14.setGeometry(QtCore.QRect(220, 52, 71, 21))
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_15 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_15.setGeometry(QtCore.QRect(280, 50, 61, 23))
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_16 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_16.setGeometry(QtCore.QRect(280, 10, 61, 23))
        self.checkBox_16.setObjectName("checkBox_16")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 703, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.checkBox.toggled['bool'].connect(self.groupBox_3.setEnabled)
        self.checkBox_2.clicked['bool'].connect(self.groupBox_4.setEnabled)
        self.radioButton_14.toggled['bool'].connect(self.groupBox_2.setEnabled)
        self.checkBox_21.toggled['bool'].connect(self.lineEdit_8.setEnabled)
        self.radioButton_4.toggled['bool'].connect(self.lineEdit_7.setEnabled)
        self.radioButton_2.toggled['bool'].connect(self.checkBox_3.setEnabled)
        self.radioButton_3.toggled['bool'].connect(self.frame.setEnabled)
        self.radioButton_2.toggled['bool'].connect(self.checkBox_18.setDisabled)
        self.checkBox_22.toggled['bool'].connect(self.toolButton.setEnabled)
        self.checkBox_20.toggled['bool'].connect(self.groupBox_7.setDisabled)
        self.checkBox_20.toggled['bool'].connect(self.groupBox_8.setDisabled)
        self.checkBox_4.toggled['bool'].connect(self.lineEdit_4.setEnabled)
        self.radioButton_4.toggled['bool'].connect(self.toolButton_2.setEnabled)
        self.checkBox_21.toggled['bool'].connect(self.lineEdit_8.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.lineEdit_2)
        MainWindow.setTabOrder(self.lineEdit_2, self.startDate)
        MainWindow.setTabOrder(self.startDate, self.endDate)
        MainWindow.setTabOrder(self.endDate, self.lineEdit)
        MainWindow.setTabOrder(self.lineEdit, self.spinBox_4)
        MainWindow.setTabOrder(self.spinBox_4, self.spinBox_5)
        MainWindow.setTabOrder(self.spinBox_5, self.lineEdit_6)
        MainWindow.setTabOrder(self.lineEdit_6, self.radioButton)
        MainWindow.setTabOrder(self.radioButton, self.radioButton_2)
        MainWindow.setTabOrder(self.radioButton_2, self.spinBox_3)
        MainWindow.setTabOrder(self.spinBox_3, self.lineEdit_5)
        MainWindow.setTabOrder(self.lineEdit_5, self.radioButton_3)
        MainWindow.setTabOrder(self.radioButton_3, self.checkBox_20)
        MainWindow.setTabOrder(self.checkBox_20, self.checkBox_19)
        MainWindow.setTabOrder(self.checkBox_19, self.checkBox_18)
        MainWindow.setTabOrder(self.checkBox_18, self.checkBox_17)
        MainWindow.setTabOrder(self.checkBox_17, self.radioButton_4)
        MainWindow.setTabOrder(self.radioButton_4, self.toolButton_2)
        MainWindow.setTabOrder(self.toolButton_2, self.lineEdit_7)
        MainWindow.setTabOrder(self.lineEdit_7, self.checkBox_21)
        MainWindow.setTabOrder(self.checkBox_21, self.lineEdit_8)
        MainWindow.setTabOrder(self.lineEdit_8, self.checkBox_22)
        MainWindow.setTabOrder(self.checkBox_22, self.toolButton)
        MainWindow.setTabOrder(self.toolButton, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.dateEdit)
        MainWindow.setTabOrder(self.dateEdit, self.dateEdit_2)
        MainWindow.setTabOrder(self.dateEdit_2, self.spinBox)
        MainWindow.setTabOrder(self.spinBox, self.comboBox_5)
        MainWindow.setTabOrder(self.comboBox_5, self.radioButton_13)
        MainWindow.setTabOrder(self.radioButton_13, self.radioButton_17)
        MainWindow.setTabOrder(self.radioButton_17, self.radioButton_15)
        MainWindow.setTabOrder(self.radioButton_15, self.radioButton_16)
        MainWindow.setTabOrder(self.radioButton_16, self.radioButton_14)
        MainWindow.setTabOrder(self.radioButton_14, self.checkBox_5)
        MainWindow.setTabOrder(self.checkBox_5, self.checkBox_6)
        MainWindow.setTabOrder(self.checkBox_6, self.checkBox_9)
        MainWindow.setTabOrder(self.checkBox_9, self.checkBox_12)
        MainWindow.setTabOrder(self.checkBox_12, self.checkBox_13)
        MainWindow.setTabOrder(self.checkBox_13, self.checkBox_16)
        MainWindow.setTabOrder(self.checkBox_16, self.checkBox_7)
        MainWindow.setTabOrder(self.checkBox_7, self.checkBox_8)
        MainWindow.setTabOrder(self.checkBox_8, self.checkBox_10)
        MainWindow.setTabOrder(self.checkBox_10, self.checkBox_11)
        MainWindow.setTabOrder(self.checkBox_11, self.checkBox_14)
        MainWindow.setTabOrder(self.checkBox_14, self.checkBox_15)
        MainWindow.setTabOrder(self.checkBox_15, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.pushButton_3)
        MainWindow.setTabOrder(self.pushButton_3, self.checkBox)
        MainWindow.setTabOrder(self.checkBox, self.pushButton_4)
        MainWindow.setTabOrder(self.pushButton_4, self.lineEdit_3)
        MainWindow.setTabOrder(self.lineEdit_3, self.radioButton_8)
        MainWindow.setTabOrder(self.radioButton_8, self.radioButton_9)
        MainWindow.setTabOrder(self.radioButton_9, self.radioButton_10)
        MainWindow.setTabOrder(self.radioButton_10, self.checkBox_2)
        MainWindow.setTabOrder(self.checkBox_2, self.spinBox_2)
        MainWindow.setTabOrder(self.spinBox_2, self.comboBox_2)
        MainWindow.setTabOrder(self.comboBox_2, self.comboBox_3)
        MainWindow.setTabOrder(self.comboBox_3, self.checkBox_3)
        MainWindow.setTabOrder(self.checkBox_3, self.checkBox_4)
        MainWindow.setTabOrder(self.checkBox_4, self.lineEdit_4)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Rolling Futures"))
        self.pushButton.setText(_translate("MainWindow", "Run"))
        self.pushButton.clicked.connect(self.setModel)
        
        self.label_3.setText(_translate("MainWindow", "Start Date"))
        self.label_4.setText(_translate("MainWindow", "End Date"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Index Ticker"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Underlying Futures"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "BBG Code"))
        self.label_10.setText(_translate("MainWindow", "Generics"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "H,H,H,M,M,M,U,U,U,Z,Z,Z"))
        self.label_11.setText(_translate("MainWindow", "Roll Schedule"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Roll Dates"))
        self.radioButton.setText(_translate("MainWindow", "LTD"))
        self.radioButton_2.setText(_translate("MainWindow", "Custom Roll Dates"))
        self.radioButton_2.clicked.connect(lambda : self.tabWidget.setCurrentIndex(1))
        self.label_8.setText(_translate("MainWindow", "Lead Days"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "Roll Amount"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Input Data"))
        self.radioButton_3.setText(_translate("MainWindow", "Database"))
        self.radioButton_4.setText(_translate("MainWindow", "Excel file"))
        self.lineEdit_7.setPlaceholderText(_translate("MainWindow", " path\\file_name.xlsx"))
        self.checkBox_20.setText(_translate("MainWindow", "Index data"))
        self.checkBox_18.setText(_translate("MainWindow", "Contract LTD"))
        self.checkBox_17.setText(_translate("MainWindow", "Price"))
        self.checkBox_19.setText(_translate("MainWindow", "Holidays"))
        self.toolButton_2.setText(_translate("MainWindow", "Browse"))
        self.toolButton_2.clicked.connect(self.openFile)

        self.groupBox_10.setTitle(_translate("MainWindow", "Ouput"))
        self.checkBox_21.setText(_translate("MainWindow", "Export to csv"))
        
        self.checkBox_22.setText(_translate("MainWindow", "Upload in Database"))
        self.lineEdit_8.setPlaceholderText(_translate("MainWindow", " File_name"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Back Test"))
        self.label.setText(_translate("MainWindow", "Start Date"))
        self.label_2.setText(_translate("MainWindow", "End Date"))
        self.comboBox_5.addItems(["Day", "Workday", "Last day","Last work Day","Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"])
        
        self.radioButton_8.setText(_translate("MainWindow", "Previous Day"))
        self.radioButton_9.setText(_translate("MainWindow", "Following Day"))
        self.radioButton_10.setText(_translate("MainWindow", "Modified Following Day"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "File Name"))
        self.label_6.setText(_translate("MainWindow", "Holiday Convention"))
        self.checkBox.setText(_translate("MainWindow", "Holidays list"))
        self.pushButton_4.setText(_translate("MainWindow", "Read File"))
        self.pushButton_4.clicked.connect(self.openFile)
 
        self.label_5.setText(_translate("MainWindow", "Generates Dates"))
        self.comboBox_2.addItems(["Days", "Workdays","Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"])
        self.comboBox_3.addItems(["After", "Before"])
        
        self.pushButton_2.setText(_translate("MainWindow", "Enter"))
        self.pushButton_2.clicked.connect(self.genCalendar)
        
        self.pushButton_3.setText(_translate("MainWindow", "Reset"))
        self.checkBox_2.setText(_translate("MainWindow", "Advanced Criteria"))
        self.groupBox1.setTitle(_translate("MainWindow", "Output"))
        self.checkBox_3.setText(_translate("MainWindow", "Export as Roll dates"))
        self.checkBox_4.setText(_translate("MainWindow", "Export to csv"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "filename.xlsx"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Recurrence"))
        self.label_7.setText(_translate("MainWindow", "Recur Every"))
        self.label_9.setText(_translate("MainWindow", "of each :"))
        self.radioButton_13.setText(_translate("MainWindow", "Week"))
        self.radioButton_14.setText(_translate("MainWindow", "Custom Months"))
        self.radioButton_15.setText(_translate("MainWindow", "Month"))
        self.radioButton_16.setText(_translate("MainWindow", "Year"))
        self.radioButton_17.setText(_translate("MainWindow", "Quater"))
        self.checkBox_5.setText(_translate("MainWindow", "Jan"))
        self.checkBox_6.setText(_translate("MainWindow", "Feb"))
        self.checkBox_7.setText(_translate("MainWindow", "Jul"))
        self.checkBox_8.setText(_translate("MainWindow", "Aug"))
        self.checkBox_9.setText(_translate("MainWindow", "Mar"))
        self.checkBox_10.setText(_translate("MainWindow", "Sep"))
        self.checkBox_11.setText(_translate("MainWindow", "Oct"))
        self.checkBox_12.setText(_translate("MainWindow", "Apr"))
        self.checkBox_13.setText(_translate("MainWindow", "May"))
        self.checkBox_14.setText(_translate("MainWindow", "Nov"))
        self.checkBox_15.setText(_translate("MainWindow", "Dec"))
        self.checkBox_16.setText(_translate("MainWindow", "Jun"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Calendar"))

    def openFile(self):
        print("Button2 pressed")
        if self.radioButton_4.isChecked():
            self.inputData_path = self.open_dialog_box()
            print(self.inputData_path)
            self.lineEdit_7.setText(self.inputData_path[-25:])
        elif self.checkBox.isChecked():
            self.hlds_path = self.open_dialog_box()
            self.lineEdit_4.setText(self.hlds_path[-20:])
        
    def open_dialog_box(self):
        filename = QFileDialog.getOpenFileName(QWidget(),'Open file',os.getcwd())
        path = filename[0]
        return str(path)
    
    ############
    def setModel(self):
        params,extras,tables,rldts = [],[True,True],[0,0,0,0],[]
        params.append(self.lineEdit_2.text())
        params.append(self.startDate.dateTime().toPyDateTime())
        params.append(self.endDate.dateTime().toPyDateTime())
        params.append(self.lineEdit.text())
        params.append(self.spinBox_4.value())
        params.append(self.spinBox_5.value())
        params.append(self.lineEdit_6.text())    ##7
        
        if self.radioButton.isChecked():
            params.append(True)     ##8
        elif self.radioButton_2.isChecked():
            params.append(False)
            rldts = self.RollDates
#            rldts = [datetime.strptime(i,"%Y-%m-%d").date() for i in roldates]
        
        params.append(self.spinBox_3.value())
        params.append(self.lineEdit_5.text())
        
        if self.radioButton_3.isChecked():
            params.append(True)
            if self.checkBox_20.isChecked() : tables[0] = 1
            if self.checkBox_19.isChecked() : tables[1] = 1
            if self.checkBox_18.isChecked() : tables[2] = 1
            if self.checkBox_17.isChecked() : tables[3] = 1
               
                
        elif self.radioButton_4.isChecked():
            params.append(False)
            extras[0] = self.inputData_path
            
        if self.checkBox_21.isChecked():
            params.append(True)
            extras[1] = self.lineEdit_8.text()
            
        else:
            params.append(False)
        if self.checkBox_22.isChecked():
            params.append(True)
            print("Upload in DB")
        else:
            params.append(False)
        
        
        print(params,tables)
        setData(params,tables,extras,rldts)
        print("Complete Run")
        
    
          

    def genCalendar(self):
        
        criteria,dates,recur,cus_mnth = [],[],[],[]
        select1 = {"Day":7, "Workday":8, "Last day":9,"Last work Day":10,"Sunday":6,"Monday":0,"Tuesday":1,"Wednesday":2,"Thursday":3,"Friday":4,"Saturday":5}
        select2 = {"Days":7, "Workdays":8,"Sunday":6,"Monday":0,"Tuesday":1,"Wednesday":2,"Thursday":3,"Friday":4,"Saturday":5}
        shift = {"After" : 1, "Before" : -1}
        
        dates.append(self.dateEdit.dateTime().toPyDateTime())
        dates.append(self.dateEdit_2.dateTime().toPyDateTime())
        
        recur.append(self.spinBox.value()-1)
        recur.append(select1[self.comboBox_5.currentText()])
        
        if self.radioButton_13.isChecked():
            window = 0
        elif self.radioButton_15.isChecked():
            window = 1
        elif self.radioButton_17.isChecked():
            window = 2
        elif self.radioButton_16.isChecked():
            window = 3
        
        criteria.append(self.radioButton_14.isChecked())
        criteria.append(self.checkBox.isChecked())
        criteria.append(self.checkBox_2.isChecked())

        if criteria[0]:
            if self.checkBox_5.isChecked() : cus_mnth.append(1)
            if self.checkBox_6.isChecked() : cus_mnth.append(2)
            if self.checkBox_9.isChecked() : cus_mnth.append(3)
            if self.checkBox_12.isChecked() : cus_mnth.append(4)
            if self.checkBox_13.isChecked() : cus_mnth.append(5)
            if self.checkBox_16.isChecked() : cus_mnth.append(6)
            if self.checkBox_7.isChecked() : cus_mnth.append(7)
            if self.checkBox_8.isChecked() : cus_mnth.append(8)
            if self.checkBox_10.isChecked() : cus_mnth.append(9)
            if self.checkBox_11.isChecked() : cus_mnth.append(10)
            if self.checkBox_14.isChecked() : cus_mnth.append(11)
            if self.checkBox_15.isChecked() : cus_mnth.append(12)
        else:
            if self.radioButton_13.isChecked() : window = 0
            elif self.radioButton_15.isChecked() : window = 1
            elif self.radioButton_17.isChecked() : window = 2
            elif self.radioButton_16.isChecked() : window = 3
            cus_mnth = list(1+np.arange(12))

            
        if criteria[1]:
#Enter holiday
            hldfile = self.lineEdit_3.text()
            Hdf = pd.read_excel(hldfile,sheet_name="Holidays")
            hol_list = list(Hdf["Date"])
            
            if self.radioButton_8.isChecked() : adj = 0
            elif self.radioButton_9.isChecked() : adj = 1
            elif self.radioButton_10.isChecked() : adj = 2
                  
        else:
            hol_list = []
            adj = 0
        
        if criteria[2] :
            print("Enter Advanced criteria (Number,Day,Preivious/After):")
            num = self.spinBox_2.value()
            day = self.comboBox_2.currentText()
            chng = self.comboBox_3.currentText()
            adv = [num,select2[day],shift[chng]]

        else :
            adv = [0,0,0]
    
        
        
        print(criteria,dates,"\n\n",recur,window)
        print(cus_mnth,adj,adv)
        self.calgen_dates = Calendar(dates[0],dates[1],window,recur[0],recur[1],cus_mnth,hol_list,adj,adv)
        
        if self.checkBox_3.isChecked():
            print(self.calgen_dates[0])
            self.RollDates = self.calgen_dates
            lambda : self.tabWidget.setCurrentIndex(0)
#Export to model
            
        if self.checkBox_4.isChecked():
            flname = self.hlds_path
            hld_df = pd.DataFrame() 
            hld_df["Dates"] = self.calgen_dates
            hld_df.to_csv(str(flname.strip(".csv"))+".csv")
            

            
       
        



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
